# Generated by Django 4.2.8 on 2024-11-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_index', '0004_rename_github_url_personaldetails_github_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon_file', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='skills_tools',
            field=models.ManyToManyField(blank=True, to='portfolio_index.skill'),
        ),
    ]
